<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TVShow;

/**
 * TVShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TVShowRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllAsQuery()
    {
        return $this->createQueryBuilder('show');
    }

    public function findByTerms($terms)
    {

        return $this->createQueryBuilder('show')
            ->where("show.name LIKE :name")
            ->orWhere("show.synopsis LIKE :name")
            ->setParameter('name', '%' . $terms . '%')
            ->getQuery()
            ->getResult();
    }

    public function insert($show){

        $this->getEntityManager()->persist($show);
        $this->getEntityManager()->flush();
    }
}
